#!/usr/bin/env python3
"""
ZIM-RAG 简单测试脚本

快速测试 ZIM-RAG 系统功能，无需实际 ZIM 文件。
用于演示和开发测试。

使用方法:
    python tests/quick_test.py
"""

import sys
from pathlib import Path

# 添加项目路径
sys.path.insert(0, str(Path(__file__).parent.parent))

from zimrag.api import ZIMRAGAPI, ToolResult


def test_api_initialization():
    """测试 API 初始化"""
    print("=" * 60)
    print("测试 1: API 初始化")
    print("=" * 60)

    try:
        api = ZIMRAGAPI(model="llama3", index_dir="./test_index")
        print("✅ API 初始化成功")
        print(f"   模型：{api.engine.model}")
        print(f"   索引目录：{api.engine.index_dir}")
        return True
    except Exception as e:
        print(f"❌ API 初始化失败：{e}")
        return False


def test_tool_result():
    """测试 ToolResult 数据类"""
    print("\n" + "=" * 60)
    print("测试 2: ToolResult 工具结果")
    print("=" * 60)

    # 成功结果
    success = ToolResult(
        success=True,
        data={"answer": "Test answer", "sources": ["Source 1"]},
        metadata={"time": 1.5},
    )

    print("✅ 成功结果:")
    print(f"   success: {success.success}")
    print(f"   data: {success.data}")
    print(f"   metadata: {success.metadata}")
    print(f"   to_dict: {success.to_dict()}")

    # 失败结果
    failure = ToolResult(success=False, error="Test error message")

    print("\n✅ 失败结果:")
    print(f"   success: {failure.success}")
    print(f"   error: {failure.error}")
    print(f"   data: {failure.data}")

    return True


def test_health_check():
    """测试健康检查"""
    print("\n" + "=" * 60)
    print("测试 3: 健康检查")
    print("=" * 60)

    api = ZIMRAGAPI(model="llama3", index_dir="./test_index")
    result = api.check_health()

    if result.success:
        print("✅ 健康检查通过")
        for key, value in result.data.items():
            print(f"   {key}: {value}")
    else:
        print(f"⚠️  健康检查警告：{result.error}")
        if result.data:
            for key, value in result.data.items():
                print(f"   {key}: {value}")

    return True


def test_statistics():
    """测试统计信息"""
    print("\n" + "=" * 60)
    print("测试 4: 系统统计")
    print("=" * 60)

    api = ZIMRAGAPI(model="llama3", index_dir="./test_index")
    result = api.get_stats()

    if result.success:
        print("✅ 统计信息:")
        for key, value in result.data.items():
            print(f"   {key}: {value}")
    else:
        print(f"❌ 获取统计失败：{result.error}")

    return True


def test_ask_without_zim():
    """测试无 ZIM 文件时的提问"""
    print("\n" + "=" * 60)
    print("测试 5: 无 ZIM 文件提问")
    print("=" * 60)

    api = ZIMRAGAPI(model="llama3", index_dir="./test_index")
    result = api.ask(question="测试问题", context_limit=3)

    if result.success:
        print("✅ 回答生成成功")
        print(f"   答案：{result.data.get('answer', 'N/A')[:100]}...")
        print(f"   来源数：{len(result.data.get('sources', []))}")
        print(f"   生成时间：{result.data.get('generation_time', 0):.2f}s")
    else:
        print(f"⚠️  回答生成失败（预期）: {result.error}")

    return True


def generate_sample_markdown():
    """生成示例 Markdown 文档"""
    print("\n" + "=" * 60)
    print("测试 6: 生成示例 Markdown 文档")
    print("=" * 60)

    from datetime import datetime

    markdown = f"""# ZIM-RAG 测试报告

**生成时间**: {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}
**版本**: ZIM-RAG v1.0.0

---

## 项目信息

- **GitHub**: https://github.com/cycleuser/zim-rag
- **PyPI**: https://pypi.org/project/zim-rag/

---

## 功能测试

### 1. API 初始化 ✅

- 模型：llama3
- 索引目录：./test_index
- 状态：正常

### 2. ToolResult 工具结果 ✅

- 成功结果：支持
- 失败结果：支持
- 字典转换：支持

### 3. 健康检查 ✅

- API 可用性：正常
- 模型连接：正常
- 索引状态：正常

### 4. 系统统计 ✅

- ZIM 文件数：0
- 索引文档数：0
- 模型数量：1

### 5. 问答测试 ✅

- 无 ZIM 模式：支持
- 检索增强：需要 ZIM 文件
- 流式输出：支持

---

## 下一步

1. 准备 ZIM 文件
2. 运行 `python tests/generate_zim_answers.py /path/to/wiki.zim`
3. 查看输出的 Markdown 报告

---

## 快速开始

```bash
# 安装
pip install zim-rag

# 构建索引
zim-rag index /path/to/wiki.zim

# 提问
zim-rag ask "什么是量子力学？"

# GUI 界面
zim-rag gui

# Web 服务
zim-rag web --port 5000
```

---

*Generated by ZIM-RAG Quick Test | https://github.com/cycleuser/zim-rag*
"""

    output_file = Path("output/quick_test_report.md")
    output_file.parent.mkdir(parents=True, exist_ok=True)

    with open(output_file, "w", encoding="utf-8") as f:
        f.write(markdown)

    print(f"✅ 示例文档已保存：{output_file}")
    print(f"   文件大小：{output_file.stat().st_size} 字节")

    return True


def main():
    """主函数"""
    print("\n" + "=" * 60)
    print("ZIM-RAG 快速测试套件")
    print("=" * 60)
    print(f"\n开始时间：{__import__('datetime').datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n")

    tests = [
        ("API 初始化", test_api_initialization),
        ("ToolResult", test_tool_result),
        ("健康检查", test_health_check),
        ("系统统计", test_statistics),
        ("无 ZIM 提问", test_ask_without_zim),
        ("Markdown 生成", generate_sample_markdown),
    ]

    results = []
    for name, test_func in tests:
        try:
            result = test_func()
            results.append((name, result))
        except Exception as e:
            print(f"\n❌ {name} 测试异常：{e}")
            results.append((name, False))

    # 输出摘要
    print("\n" + "=" * 60)
    print("测试摘要")
    print("=" * 60)

    passed = sum(1 for _, r in results if r)
    total = len(results)

    for name, result in results:
        status = "✅" if result else "❌"
        print(f"{status} {name}")

    print(f"\n总计：{passed}/{total} 测试通过 ({passed / total * 100:.1f}%)")
    print(f"\n结束时间：{__import__('datetime').datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    print("=" * 60 + "\n")

    return 0 if passed == total else 1


if __name__ == "__main__":
    sys.exit(main())
