#!/usr/bin/env python3
"""
墨子/墨家资料整理脚本

从指定的 ZIM 文件中检索关于墨子和墨家的所有资料，整理为 Markdown 文档。

使用方法:
    python tests/search_mozi.py
"""

import sys
import time
from pathlib import Path
from datetime import datetime
from typing import List, Dict

# 添加项目路径
sys.path.insert(0, str(Path(__file__).parent.parent))

from zimrag.api import ZIMRAGAPI, ToolResult


# 墨子/墨家相关问题列表（由浅入深）
MOZI_QUESTIONS = [
    # 基础问题
    "墨子是谁？",
    "墨子生活在什么时代？",
    "墨子的生平简介",
    "墨子出生于哪里？",
    # 墨家思想
    "什么是墨家？",
    "墨家的主要思想是什么？",
    "墨子的核心思想有哪些？",
    "兼爱非攻是什么意思？",
    "墨子的兼爱思想内容",
    "墨子的非攻思想内容",
    "墨子的尚贤思想",
    "墨子的尚同思想",
    "墨子的天志思想",
    "墨子的明鬼思想",
    "墨子的非命思想",
    "墨子的非乐思想",
    "墨子的节用思想",
    "墨子的节葬思想",
    # 墨家组织
    "墨家的组织结构",
    "墨家的领袖传承",
    "墨家巨子是谁？",
    "墨家的代表人物",
    # 墨子著作
    "《墨子》这本书的内容",
    "《墨子》有多少篇？",
    "墨子的著作有哪些？",
    "墨经的内容是什么？",
    # 科学技术
    "墨子的科学成就",
    "墨子的光学研究",
    "墨子的力学贡献",
    "墨子的几何学成就",
    "墨子的物理学贡献",
    "墨子的小孔成像",
    "墨子的机械制造",
    "墨子的守城技术",
    # 历史影响
    "墨家的历史地位",
    "墨家与儒家的区别",
    "墨家为什么衰落？",
    "墨家思想的影响",
    "墨子的历史评价",
    "墨家在战国时期的影响",
    # 比较研究
    "墨子和孔子思想对比",
    "墨家和儒家有什么不同",
    "墨家与道家的区别",
    "墨家与法家的区别",
    # 现代研究
    "现代对墨子的研究",
    "墨学研究的现状",
    "墨子思想的现代价值",
]


def format_mozi_markdown(answers: List[Dict], zim_files: List[str], output_file: str) -> str:
    """格式化墨子资料为 Markdown 文档"""

    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    md = f"""# 墨子与墨家资料汇编

**生成时间**: {timestamp}  
**数据来源**: ZIM-RAG 本地知识库检索系统  
**ZIM 文件**: {", ".join(Path(f).name for f in zim_files)}  
**问题数量**: {len(answers)}

---

## 目录

1. [墨子简介](#墨子简介)
2. [墨家思想](#墨家思想)
3. [墨家组织](#墨家组织)
4. [墨子著作](#墨子著作)
5. [科学技术成就](#科学技术成就)
6. [历史地位与影响](#历史地位与影响)
7. [比较研究](#比较研究)
8. [现代研究](#现代研究)

---

## 墨子简介

"""

    # 分类整理答案
    categories = {
        "简介": ["墨子是谁", "墨子生活在", "墨子的生平", "墨子出生"],
        "思想": [
            "墨家",
            "兼爱",
            "非攻",
            "尚贤",
            "尚同",
            "天志",
            "明鬼",
            "非命",
            "非乐",
            "节用",
            "节葬",
            "核心思想",
        ],
        "组织": ["组织结构", "领袖", "巨子", "代表人物", "传承"],
        "著作": ["《墨子》", "墨经", "著作", "多少篇"],
        "科技": ["科学", "光学", "力学", "几何", "物理", "小孔成像", "机械", "守城"],
        "历史": ["历史地位", "儒家", "衰落", "影响", "评价", "战国"],
        "比较": ["对比", "不同", "区别"],
        "现代": ["现代", "现状", "价值", "墨学研究"],
    }

    for answer in answers:
        question = answer.get("question", "Unknown")
        answer_text = answer.get("answer", "N/A")
        sources = answer.get("sources", [])
        category = answer.get("category", "其他")

        # 跳过空答案或错误答案
        if not answer_text or answer_text.startswith("Error:") or answer_text.startswith("❌"):
            continue

        md += f"""### {question}

{answer_text}

"""

        if sources:
            md += "**参考资料**:\n"
            for i, source in enumerate(sources, 1):
                title = source.get("title", "Unknown")
                url = source.get("url", "")
                if url:
                    md += f"{i}. [{title}]({url})\n"
                else:
                    md += f"{i}. {title}\n"

        md += "\n---\n\n"

    # 添加统计信息
    valid_answers = [
        a
        for a in answers
        if a.get("answer") and not a.get("answer", "").startswith(("Error:", "❌"))
    ]

    md += f"""## 附录：统计信息

| 项目 | 数量 |
|------|------|
| 总问题数 | {len(answers)} |
| 有效回答数 | {len(valid_answers)} |
| ZIM 文件数 | {len(zim_files)} |
| 平均来源数 | {sum(len(a.get("sources", [])) for a in valid_answers) / max(1, len(valid_answers)):.1f} |

---

## 关于本文档

本文档由 ZIM-RAG 系统自动生成，所有内容来源于本地 ZIM 知识库文件。

**项目信息**:
- GitHub: https://github.com/cycleuser/zim-rag
- PyPI: https://pypi.org/project/zim-rag/
- 许可证：GPL-3.0

**生成参数**:
- 模型：Ollama (llama3)
- 上下文限制：5
- 检索方式：向量语义检索

---

*Generated by ZIM-RAG Mozi Research Tool v1.0.0*
"""

    return md


def search_mozi_knowledge(zim_paths: List[str], output_dir: str = "output") -> Dict:
    """
    从 ZIM 文件中搜索墨子/墨家相关资料

    Args:
        zim_paths: ZIM 文件路径列表
        output_dir: 输出目录

    Returns:
        搜索结果字典
    """
    output_path = Path(output_dir)
    output_path.mkdir(parents=True, exist_ok=True)

    print("=" * 70)
    print("墨子/墨家资料检索与整理")
    print("=" * 70)
    print(f"\n📦 ZIM 文件：{len(zim_paths)}")
    for zim in zim_paths:
        zim_size = Path(zim).stat().st_size / (1024**3)
        print(f"   - {Path(zim).name} ({zim_size:.1f} GB)")
    print(f"\n📝 问题数量：{len(MOZI_QUESTIONS)}")
    print(f"📂 输出目录：{output_path}\n")

    # 初始化 API
    api = ZIMRAGAPI(model="llama3", index_dir=str(output_path / "mozi_index"))

    results = {
        "timestamp": datetime.now().isoformat(),
        "zim_files": zim_paths,
        "questions": MOZI_QUESTIONS,
        "answers": [],
    }

    # 为每个 ZIM 文件构建索引并搜索
    for zim_idx, zim_path in enumerate(zim_paths):
        print(f"\n{'=' * 70}")
        print(f"处理 ZIM 文件 {zim_idx + 1}/{len(zim_paths)}: {Path(zim_path).name}")
        print(f"{'=' * 70}")

        # 重置索引
        api.engine.index = None

        # 添加 ZIM 文件
        print(f"\n📖 加载 ZIM 文件...")
        result = api.add_zim(zim_path)
        if not result.success:
            print(f"❌ 加载失败：{result.error}")
            continue

        # 构建索引
        print(f"🔨 构建索引 (可能需要数分钟)...")
        start_time = time.time()
        result = api.build_index(max_articles=5000, chunk_size=500)
        index_time = time.time() - start_time

        if not result.success:
            print(f"❌ 索引构建失败：{result.error}")
            continue

        print(f"✅ 索引构建完成 ({index_time:.1f}秒)")

        # 对每个问题进行搜索
        for q_idx, question in enumerate(MOZI_QUESTIONS, 1):
            print(f"\r  问题 {q_idx}/{len(MOZI_QUESTIONS)}: {question[:30]}...", end="", flush=True)

            # 确定类别
            category = "其他"
            for cat, keywords in [
                ("简介", ["谁", "时代", "生平", "出生"]),
                (
                    "思想",
                    [
                        "墨家",
                        "兼爱",
                        "非攻",
                        "尚贤",
                        "尚同",
                        "天志",
                        "明鬼",
                        "非命",
                        "非乐",
                        "节用",
                        "节葬",
                        "思想",
                    ],
                ),
                ("组织", ["组织", "领袖", "巨子", "人物", "传承"]),
                ("著作", ["墨子》", "墨经", "著作", "篇"]),
                ("科技", ["科学", "光学", "力学", "几何", "物理", "小孔", "机械", "守城"]),
                ("历史", ["历史", "儒家", "衰落", "影响", "评价", "战国"]),
                ("比较", ["对比", "不同", "区别"]),
                ("现代", ["现代", "现状", "价值", "研究"]),
            ]:
                if any(kw in question for kw in keywords):
                    category = cat
                    break

            # 提问
            result = api.ask(question=question, context_limit=5, model="llama3")

            answer_entry = {
                "question": question,
                "category": category,
                "zim_file": zim_path,
            }

            if result.success:
                answer_data = result.data
                answer_entry.update(
                    {
                        "answer": answer_data.get("answer", "N/A"),
                        "sources": answer_data.get("sources", []),
                        "retrieval_time": answer_data.get("retrieval_time", 0),
                        "generation_time": answer_data.get("generation_time", 0),
                        "model": answer_data.get("model", "llama3"),
                    }
                )
            else:
                answer_entry["answer"] = f"Error: {result.error}"
                answer_entry["sources"] = []

            results["answers"].append(answer_entry)

        print()  # 换行

    # 生成 Markdown 文档
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    output_file = output_path / f"墨子墨家资料汇编_{timestamp}.md"

    md_content = format_mozi_markdown(
        answers=results["answers"], zim_files=zim_paths, output_file=str(output_file)
    )

    with open(output_file, "w", encoding="utf-8") as f:
        f.write(md_content)

    # 统计信息
    valid_answers = len(
        [a for a in results["answers"] if not a.get("answer", "").startswith(("Error:", "❌"))]
    )

    print(f"\n{'=' * 70}")
    print(f"✅ 资料整理完成！")
    print(f"{'=' * 70}")
    print(f"\n📊 统计信息:")
    print(f"   总问题数：{len(results['answers'])}")
    print(f"   有效回答：{valid_answers}")
    print(f"   成功率：{valid_answers / len(results['answers']) * 100:.1f}%")
    print(f"\n📄 输出文件：{output_file}")
    print(f"\n{'=' * 70}\n")

    return results


def main():
    """主函数"""
    # 指定的 ZIM 文件
    zim_files = [
        "/media/fred/Data/Wiki/wikipedia_zh_all_maxi_2024-04.zim",
        "/media/fred/Data/Wiki/wikibooks_en_all_maxi_2021-03.zim",
    ]

    # 验证文件存在
    valid_zims = [f for f in zim_files if Path(f).exists()]

    if not valid_zims:
        print("❌ 错误：指定的 ZIM 文件不存在")
        for f in zim_files:
            print(f"   - {f}")
        sys.exit(1)

    if len(valid_zims) < len(zim_files):
        print("⚠️  警告：部分 ZIM 文件不存在，跳过")
        for f in zim_files:
            if f not in valid_zims:
                print(f"   - {f}")

    # 执行搜索
    results = search_mozi_knowledge(zim_paths=valid_zims, output_dir="output")

    return 0


if __name__ == "__main__":
    sys.exit(main())
